### ISSUE TITLE
trim down the repo

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/BioSimSpaceTutorials#31] opened 2023-06-29 12:31 UTC
the repo currently uses close to 1 GB

```
(base) julien@yoko:~/projects/BioSimSpaceTutorials$ du -sch *
3.9M	01_introduction
141M	02_funnel_metad
17M	03_steered_md
697M	04_fep
372K	LIVECOMS
4.0K	README.md
8.0K	Style_guide.ipynb
858M	total
```

We should be able to reduce this to just a few MB by moving all inputs to the notebooks to another repo and updating the notebooks to download inputs as needed.

**Comment by lohedges** [comment] 2023-06-29 12:34
Duplicate of #20 ;-)

**Comment by jmichel80** [comment] 2023-06-29 12:40
i think this is different from #20 as it requires updating the notebooks

**Comment by lohedges** [comment] 2023-06-29 12:45
Yes, I guess this is a multi-step process :+1:

**Comment by jmichel80** [comment] 2023-06-29 12:46
we should also generate and add to the repo markdown versions of the notebooks with the cells output once the content of the input cells has been finalised.

**Comment by jmichel80** [comment] 2023-07-02 07:37
Having gone through all tutorials I have [reduced the total footprint ](https://github.com/OpenBioSim/BioSimSpaceTutorials/tree/trim_tutorials)by a factor of x5. 
There are so many file changes that I can't create a PR via the web UI. 

```
(base) julien@yoko:~/projects/BioSimSpaceTutorials$ du -sch *
1.6M	01_introduction
15M	02_funnel_metad
3.8M	03_steered_md
142M	04_fep
372K	LIVECOMS
4.0K	README.md
8.0K	Style_guide.ipynb
162M	total
```
All the datasets needed have been added to compressed tarballs.  Once the datasets are moved out of the repo the maximum amount of data that needs to be downloaded to go through all the tutorials will be < 100 MB.  Going through the tutorials still currently requires extracting the tar files so the actual footprint during use of the tutorials will be larger.

More optimisations are possible but this could be time consuming.

**Closed** 2023-07-06 22:41 UTC
